/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.login;

import domen.Referent;
import forme.glavna.FGlavna;
import java.io.IOException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import klijent.Klijent;
import kontroler.Kontroler;

/**
 *
 * @author Bodin Todorovic
 */
public class FRegistrovanjeReferenta extends javax.swing.JFrame {

    /**
     * Creates new form FRegistrovanjeReferenta
     */
    public FRegistrovanjeReferenta() {
        initComponents();
        setLocationRelativeTo(null);
//        Klijent.getInstanca().poveziSe();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxtKorisnickoIme = new javax.swing.JTextField();
        jbtnUlogujSe = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jtxtPort = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtIPAdresa = new javax.swing.JTextField();
        jpfLozinka = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registrovanje referenta");

        jLabel1.setText("Korisnicko ime:");

        jLabel2.setText("Lozinka:");

        jbtnUlogujSe.setText("Uloguj Se");
        jbtnUlogujSe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUlogujSeActionPerformed(evt);
            }
        });

        jLabel3.setText("Port:");

        jLabel4.setText("IP adresa:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbtnUlogujSe)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxtKorisnickoIme)
                            .addComponent(jtxtPort, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                            .addComponent(jtxtIPAdresa, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                            .addComponent(jpfLozinka))))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtKorisnickoIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jpfLozinka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxtIPAdresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(jbtnUlogujSe)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnUlogujSeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUlogujSeActionPerformed
        try {                                             
            String korisnickoIme = jtxtKorisnickoIme.getText().trim();
            String lozinka = jpfLozinka.getText().trim();
            String IPAdresa = jtxtIPAdresa.getText().trim();
            int port;
            try {
                port = Integer.parseInt(jtxtPort.getText().trim());
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(this, "Unesite broj u polje 'Port'");
                return;
            }
            
            konektujSe(IPAdresa, port);
            
            if (izvrsiValidaciju(korisnickoIme, lozinka) == true) {
                JFrame glavna = new FGlavna();
                glavna.setVisible(true);
                dispose();
                JOptionPane.showMessageDialog(glavna, "Uspesno ste se ulogovali");
            } else {
                JOptionPane.showMessageDialog(this, "Kombinacija korisnicko ime/lozinka je netacna");
                diskonektujSe();
            }
        } catch (Exception ex) {
//            Logger.getLogger(FRegistrovanjeReferenta.class.getName()).log(Level.SEVERE, null,ex);
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jbtnUlogujSeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jbtnUlogujSe;
    private javax.swing.JPasswordField jpfLozinka;
    private javax.swing.JTextField jtxtIPAdresa;
    private javax.swing.JTextField jtxtKorisnickoIme;
    private javax.swing.JTextField jtxtPort;
    // End of variables declaration//GEN-END:variables

    public boolean izvrsiValidaciju(String korisnickoIme, String lozinka) {
        try {
            Referent referent = new Referent();
            referent.setKorisnickoIme(korisnickoIme);
            referent.setLozinka(lozinka);
            
            referent = Kontroler.getInstanca().ulogujReferenta(referent);
            Kontroler.getInstanca().postaviTrenutnogReferenta(referent);
            return true;
        } catch (Exception ex) {
//            Logger.getLogger(FRegistrovanjeReferenta.class.getName()).log(Level.SEVERE, null, ex);
            return false;
        }
    }

    private void konektujSe(String IPAdresa, int port) throws Exception {
        Klijent.getInstanca().poveziSe(IPAdresa, port);
    }

    private void diskonektujSe() {
        try {
            Klijent.getInstanca().getSocket().close();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Doslo je do ne predvidjene greske, prinudno se zatvara aplikacija");
            dispose();
            Logger.getLogger(FRegistrovanjeReferenta.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println("Diskonektovao se");
    }
}
