/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.glavna;

import forme.prenociste.FPrikazPrenocista;
import forme.prenociste.FUnosPrenocista;
import forme.stanar.FPrikazStanara;
import forme.stanar.FUnosStanara;
import forme.zaduzenje_inventara.FPrikazZaduzenjaInventara;
import forme.zaduzenje_inventara.FUnosZaduzenjaInventara;
import java.awt.BorderLayout;
import javax.swing.JDialog;
import javax.swing.JFrame;
import kontroler.Kontroler;

/**
 *
 * @author Bodin Todorovic
 */
public class FGlavna extends javax.swing.JFrame {

    /**
     * Creates new form FGlavna
     */
    public FGlavna() {
        initComponents();
        setLocationRelativeTo(null);
        srediLabelu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblReferent = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiPrikazStanara = new javax.swing.JMenuItem();
        jmiUnosStanara = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmiPrikazPrenocista = new javax.swing.JMenuItem();
        jmiUnosPrenocita = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmiPrikazZaduzenja = new javax.swing.JMenuItem();
        jmiUnosZaduzenja = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Klijent");

        jMenu1.setText("Stanar");

        jmiPrikazStanara.setText("Prikaz stanara");
        jmiPrikazStanara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPrikazStanaraActionPerformed(evt);
            }
        });
        jMenu1.add(jmiPrikazStanara);

        jmiUnosStanara.setText(" Unos stanara");
        jmiUnosStanara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUnosStanaraActionPerformed(evt);
            }
        });
        jMenu1.add(jmiUnosStanara);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Prenociste");

        jmiPrikazPrenocista.setText("Prikaz prenocista");
        jmiPrikazPrenocista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPrikazPrenocistaActionPerformed(evt);
            }
        });
        jMenu2.add(jmiPrikazPrenocista);

        jmiUnosPrenocita.setText("Unos prenocista");
        jmiUnosPrenocita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUnosPrenocitaActionPerformed(evt);
            }
        });
        jMenu2.add(jmiUnosPrenocita);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Zaduzenje inventara");

        jmiPrikazZaduzenja.setText("Prikaz zaduzenja");
        jmiPrikazZaduzenja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPrikazZaduzenjaActionPerformed(evt);
            }
        });
        jMenu3.add(jmiPrikazZaduzenja);

        jmiUnosZaduzenja.setText("Unos zaduzenja");
        jmiUnosZaduzenja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiUnosZaduzenjaActionPerformed(evt);
            }
        });
        jMenu3.add(jmiUnosZaduzenja);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jlblReferent, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jlblReferent, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(214, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiPrikazStanaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPrikazStanaraActionPerformed
        // TODO add your handling code here:
//        JFrame f = new FStanar();
//        f.setVisible(true);
        FPrikazStanara f = new FPrikazStanara();
        JDialog d = new JDialog(this, "Prikaz stanara", true);
        d.setLayout(new BorderLayout());
        d.add(f, BorderLayout.CENTER);
        d.pack();
        d.setLocationRelativeTo(null);
        d.setVisible(true);
    }//GEN-LAST:event_jmiPrikazStanaraActionPerformed

    private void jmiUnosStanaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUnosStanaraActionPerformed
        // TODO add your handling code here:
        FUnosStanara f = new FUnosStanara();
        JDialog d = new JDialog(this, "Unos stanara", true);
        d.setLayout(new BorderLayout());
        d.add(f, BorderLayout.CENTER);
        d.pack();
        d.setLocationRelativeTo(null);
        d.setVisible(true);
    }//GEN-LAST:event_jmiUnosStanaraActionPerformed

    private void jmiPrikazPrenocistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPrikazPrenocistaActionPerformed
        // TODO add your handling code here:
        FPrikazPrenocista f = new FPrikazPrenocista();
        JDialog d = new JDialog(this, "Prikaz prenocista", true);
        d.setLayout(new BorderLayout());
        d.add(f, BorderLayout.CENTER);
        d.pack();
        d.setLocationRelativeTo(null);
        d.setVisible(true);
    }//GEN-LAST:event_jmiPrikazPrenocistaActionPerformed

    private void jmiUnosPrenocitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUnosPrenocitaActionPerformed
        // TODO add your handling code here:
        FUnosPrenocista f = new FUnosPrenocista();
        JDialog d = new JDialog(this, "Unos prenocista", true);
        d.setLayout(new BorderLayout());
        d.add(f, BorderLayout.CENTER);
        d.pack();
        d.setLocationRelativeTo(null);
        d.setVisible(true);
    }//GEN-LAST:event_jmiUnosPrenocitaActionPerformed

    private void jmiPrikazZaduzenjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPrikazZaduzenjaActionPerformed
        // TODO add your handling code here:
        FPrikazZaduzenjaInventara f = new FPrikazZaduzenjaInventara();
        JDialog d = new JDialog(this, "Prikaz zaduzenja inventara", true);
        d.setLayout(new BorderLayout());
        d.add(f, BorderLayout.CENTER);
        d.pack();
        d.setLocationRelativeTo(null);
        d.setVisible(true);
    }//GEN-LAST:event_jmiPrikazZaduzenjaActionPerformed

    private void jmiUnosZaduzenjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiUnosZaduzenjaActionPerformed
        // TODO add your handling code here:
        FUnosZaduzenjaInventara f = new FUnosZaduzenjaInventara();
        JDialog d = new JDialog(this, "Unos zaduzenja inventara", true);
        d.setLayout(new BorderLayout());
        d.add(f, BorderLayout.CENTER);
        d.pack();
        d.setLocationRelativeTo(null);
        d.setVisible(true);
    }//GEN-LAST:event_jmiUnosZaduzenjaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel jlblReferent;
    private javax.swing.JMenuItem jmiPrikazPrenocista;
    private javax.swing.JMenuItem jmiPrikazStanara;
    private javax.swing.JMenuItem jmiPrikazZaduzenja;
    private javax.swing.JMenuItem jmiUnosPrenocita;
    private javax.swing.JMenuItem jmiUnosStanara;
    private javax.swing.JMenuItem jmiUnosZaduzenja;
    // End of variables declaration//GEN-END:variables

    private void srediLabelu() {
        jlblReferent.setText("Ulogovani ste kao: " + Kontroler.getInstanca().vratiTrenutnogReferenta().toString());
        jlblReferent.setVisible(true);
    }
}
